base_config: "base.yml"

use_sft: True
train_data_columns: ['inputs']
eval_data_columns: ['inputs']

per_device_batch_size: 1.0
steps: 10
max_target_length: 1024
eval_interval: 5  # test eval once, in the middle of 10 training steps
eval_steps: 2

# HF pipeline
dataset_type: hf
hf_path: 'HuggingFaceH4/ultrachat_200k'
hf_train_split: 'train_sft'
hf_eval_split: 'test_sft'

enable_goodput_recording: False
monitor_goodput: False
enable_checkpointing: True